import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import { listProfiles, getProfile, saveProfile, getCatalog, createRun, getSetup, validateTarget, DEMO_MODE } from "./api";
import type { ProfileInput, Profile, ReadinessCheck } from "./types";
export function Failure({error,retry}:{error:unknown;retry?:()=>void}){return <div className="state-panel state-error" role="alert"><div><h2>Не удалось получить данные</h2><p>{error instanceof Error?error.message:"Неизвестная ошибка"}</p>{retry&&<button className="button button-secondary" onClick={retry}>Повторить запрос</button>}</div></div>;}
function Header({title,children}:{title:string;children?:React.ReactNode}){return <div className="page-header"><h1>{title}</h1>{children}</div>;}
export function Checks({checks}:{checks:ReadinessCheck[]}){const labels:Record<string,string>={ready:"Готово",blocked:"Заблокировано",optional:"Необязательно",unknown:"Не проверено",missing:"Не настроено"};return <div className="settings-checks">{checks.map(c=><div className="settings-check" key={c.id}><div><strong>{c.label||c.id}</strong><span>{c.reason||c.detail}</span></div><span>{labels[c.status]??c.status}</span></div>)}</div>;}
function ProfileCard({profile}:{profile:Profile}){
 const validate=useMutation({mutationFn:()=>validateTarget(profile.id)});
 return <section className="target-profile-card"><h2>{profile.name}</h2><p>{profile.adapter} · версия {profile.version}</p><code>{profile.config.base_url}</code><dl>{Object.entries(profile.actor_status??{}).map(([role,status])=><div key={role}><dt>{role} · {status.cus}</dt><dd>{Object.values(status.credential_refs).join(", ")||"Ссылки не заданы"} — {status.configured?"настроено":"не настроено"}</dd></div>)}</dl>
 <div className="target-card-actions"><Link className="button button-secondary" to={"/targets/"+encodeURIComponent(profile.id)+"/edit"}>Редактировать профиль</Link><button className="button button-secondary" disabled={validate.isPending} onClick={()=>validate.mutate()}>{validate.isPending?"Проверяем…":"Проверить подключение"}</button><Link className="button button-primary" to={"/runs/new?target="+encodeURIComponent(profile.id)}>Новый запуск</Link></div>
 {validate.isError&&<Failure error={validate.error}/>} {validate.data&&<div role="status"><Checks checks={validate.data.checks}/></div>}</section>;
}
export function TargetsPage(){
 const q=useQuery({queryKey:["profiles"],queryFn:({signal})=>listProfiles(signal)});
 return <div><Header title="Цели"><Link className="button button-primary" to="/targets/new">Подключить цель</Link></Header><p>Профиль хранит адрес, роли и ссылки на секреты. Проверка подключения не запускает эксперимент.</p>
 {q.isPending?<p role="status">Загружаем цели…</p>:q.isError?<Failure error={q.error} retry={()=>q.refetch()}/>:q.data.length?<div className="profile-list">{q.data.map(p=><ProfileCard key={p.id} profile={p}/>)}</div>:<div className="state-panel"><h2>Цели ещё не подключены</h2><p>Добавьте профиль цели, чтобы настроить эксперимент.</p></div>}</div>;
}
const blank:ProfileInput={schema_version:1,id:"",name:"",adapter:"investment-stand",base_url:"",actors:{},lifecycle:{},adapter_options:{}};
function ProfileForm({initial,editing}:{initial:ProfileInput;editing:boolean}){
 const [form,setForm]=useState(initial),[actors,setActors]=useState(JSON.stringify(initial.actors,null,2)),[lifecycle,setLifecycle]=useState(JSON.stringify(initial.lifecycle,null,2)),[options,setOptions]=useState(JSON.stringify(initial.adapter_options,null,2)),[error,setError]=useState("");
 const cache=useQueryClient(),navigate=useNavigate();
 const mutation=useMutation({mutationFn:(input:ProfileInput)=>saveProfile(input,editing),onSuccess:()=>{void cache.invalidateQueries({queryKey:["profiles"]});void cache.invalidateQueries({queryKey:["profile"]});void cache.invalidateQueries({queryKey:["setup"]});navigate("/targets");}});
 const parseObject=(s:string)=>{const o=JSON.parse(s);if(!o||Array.isArray(o)||typeof o!=="object")throw new Error("Ожидается JSON-объект");return o;};
 function submit(e:React.FormEvent){e.preventDefault();setError("");try{
 const u=new URL(form.base_url);if(!["http:","https:"].includes(u.protocol)||u.username||u.password)throw new Error("Укажите HTTP(S) URL без логина и пароля.");
 const mapping=parseObject(actors);
 for(const [role,entry] of Object.entries(mapping)){const a=entry as Record<string,unknown>;if(!a||typeof a!=="object"||!a.cus)throw new Error("У роли "+role+" требуется cus.");for(const key of Object.keys(a)){if(!["cus","credential_env","credential_file","access_token_env","access_token_file","attributes"].includes(key))throw new Error("Недопустимое поле роли: "+key);}for(const key of ["credential_env","access_token_env"]){if(a[key]&&!/^[A-Z][A-Z0-9_]{1,127}$/.test(String(a[key])))throw new Error("Укажите имя переменной окружения, а не значение секрета.");}}
 mutation.mutate({...form,actors:mapping,lifecycle:parseObject(lifecycle),adapter_options:parseObject(options)});
 }catch(err){setError(err instanceof Error?err.message:"Проверьте конфигурацию");}}
 return <form onSubmit={submit} className="form-layout"><section className="form-panel"><h2>Профиль цели</h2><div className="form-grid">{(["id","name","adapter","base_url"] as const).map(key=><label className="form-field" key={key}><span>{{id:"ID профиля",name:"Название",adapter:"Адаптер",base_url:"Адрес HTTP API"}[key]}</span><input required value={form[key]} disabled={key==="id"&&editing} maxLength={key==="name"?160:key==="base_url"?2048:120} pattern={key==="id"?"[a-z0-9][a-z0-9_.-]{0,79}":undefined} type={key==="base_url"?"url":"text"} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div>
 <p>Секреты вводятся в окружении сервера. Здесь задаются только ссылки на переменные или файлы.</p></section>
 <section className="form-panel"><h2>Роли и credentials</h2><p>Каждая роль содержит cus и credential_env. При необходимости задайте access_token_env.</p><label className="form-field"><span>Роли (JSON)</span><textarea rows={10} value={actors} onChange={e=>setActors(e.target.value)} spellCheck={false}/></label><button type="button" className="button button-secondary" onClick={()=>setActors(JSON.stringify({attacker:{cus:"1001",credential_env:"DISKARD_ATTACKER_TARGET_KEY"},trigger_user:{cus:"1002",credential_env:"DISKARD_TRIGGER_TARGET_KEY"},data_subject:{cus:"1003",credential_env:"DISKARD_SUBJECT_TARGET_KEY",access_token_env:"DISKARD_SUBJECT_TARGET_TOKEN"},control:{cus:"1004",credential_env:"DISKARD_CONTROL_TARGET_KEY"}},null,2))}>Заполнить роли инвестиционного стенда</button></section>
 <details className="advanced-panel"><summary>Lifecycle и параметры адаптера</summary><label className="form-field"><span>Lifecycle (JSON)</span><textarea value={lifecycle} onChange={e=>setLifecycle(e.target.value)} rows={5}/></label><label className="form-field"><span>Параметры адаптера (JSON, только несекретные значения и ссылки)</span><textarea value={options} onChange={e=>setOptions(e.target.value)} rows={6}/></label></details>
 <div className="form-actions"><button className="button button-primary" disabled={mutation.isPending}>{mutation.isPending?"Сохраняем…":editing?"Сохранить новую версию":"Создать профиль"}</button><Link to="/targets" className="button button-secondary">Отмена</Link></div>
 {(error||mutation.isError)&&<Failure error={error?new Error(error):mutation.error}/>}</form>;
}
export function NewTargetPage(){const {id}=useParams();const q=useQuery({queryKey:["profile",id],queryFn:({signal})=>getProfile(id!,signal),enabled:!!id});return <div><Header title={id?"Редактирование цели":"Новая цель"}><Link to="/targets" className="button button-secondary">К целям</Link></Header>{id&&q.isPending?<p>Загружаем профиль…</p>:id&&q.isError?<Failure error={q.error} retry={()=>q.refetch()}/>:<ProfileForm key={id??"new"} initial={q.data?.config??blank} editing={!!id}/>}</div>;}
export function NewRunPage(){
 const navigate=useNavigate(),cache=useQueryClient(),profiles=useQuery({queryKey:["profiles"],queryFn:({signal})=>listProfiles(signal)});
 const [selected,setSelected]=useState(new URLSearchParams(location.search).get("target")??""),[attack,setAttack]=useState(""),[driver,setDriver]=useState(""),[budget]=useState(1),[submissionId]=useState(()=>crypto.randomUUID());
 const target=selected||profiles.data?.[0]?.id||"";
 const catalog=useQuery({queryKey:["catalog",target],queryFn:({signal})=>getCatalog(target,signal),enabled:!!target});
 const selectedAttack=catalog.data?.attacks.find(a=>a.id===attack&&a.available)?.id??catalog.data?.attacks.find(a=>a.available)?.id??"";
 const selectedDriver=catalog.data?.drivers.find(a=>a.id===driver&&a.available)?.id??catalog.data?.drivers.find(a=>a.available)?.id??"";
 const mutation=useMutation({mutationFn:()=>createRun({profile_id:target,attack:selectedAttack,driver:selectedDriver,budget,repeat:1,submission_id:submissionId}),onSuccess:r=>{void cache.invalidateQueries({queryKey:["runs"]});navigate("/runs/"+encodeURIComponent(r.id)+"/trace");}});
 return <div><Header title="Новый запуск"><Link to="/runs" className="button button-secondary">К запускам</Link></Header>{profiles.isPending?<p>Загружаем цели…</p>:profiles.isError?<Failure error={profiles.error} retry={()=>profiles.refetch()}/>:!profiles.data.length?<div className="state-panel"><h2>Сначала подключите цель</h2><Link to="/targets/new" className="button button-primary">Подключить цель</Link></div>:<form className="new-run-layout" onSubmit={e=>{e.preventDefault();if(!mutation.isPending)mutation.mutate();}}>
 <section className="form-panel"><h2>Конфигурация эксперимента</h2><label className="form-field"><span>Профиль цели</span><select value={target} onChange={e=>{setSelected(e.target.value);setAttack("");setDriver("");}}>{profiles.data.map(p=><option key={p.id} value={p.id}>{p.name} · v{p.version}</option>)}</select></label>
 {catalog.isPending?<p>Загружаем сценарии…</p>:catalog.isError?<Failure error={catalog.error} retry={()=>catalog.refetch()}/>:<>{[["Сценарий",catalog.data.attacks,selectedAttack,setAttack],["Драйвер",catalog.data.drivers,selectedDriver,setDriver]].map(([label,items,value,setter])=><label className="form-field" key={String(label)}><span>{String(label)}</span><select required value={String(value)} onChange={e=>(setter as (v:string)=>void)(e.target.value)}><option value="" disabled>Выберите доступный вариант</option>{(items as typeof catalog.data.attacks).map(a=><option disabled={!a.available} value={a.id} key={a.id}>{a.label??a.id}{!a.available?" — недоступен":""}</option>)}</select></label>)}<div>{[...catalog.data.attacks,...catalog.data.drivers].filter(i=>!i.available&&i.reason).map(i=><p key={i.id}>{i.label??i.id}: {i.reason}</p>)}</div></>}
 <label className="form-field"><span>Бюджет попыток</span><input type="number" value={budget} readOnly aria-describedby="budget-help"/><small id="budget-help">Фиксированный вход: одна попытка. Поиск и групповые повторы пока недоступны.</small></label></section>
 <aside className="run-readiness-panel"><h2>Перед запуском</h2><p>Запуск создаётся с текущей версией профиля. Доступность сценария и credentials проверяет сервер.</p><p>Один эксперимент за отправку. Групповые повторы пока не поддерживаются backend.</p>{catalog.data?.limitations.map((s,i)=><p key={i}>{s}</p>)}<button className="button button-primary" disabled={mutation.isPending||!selectedAttack||!selectedDriver||catalog.isFetching||!Number.isInteger(budget)||budget<1||budget>100}>{mutation.isPending?"Создаём…":DEMO_MODE?"Создать demo-запуск":"Создать запуск"}</button>{mutation.isError&&<Failure error={mutation.error}/>}</aside></form>}</div>;
}
export function SettingsPage(){
 const q=useQuery({queryKey:["setup"],queryFn:({signal})=>getSetup(signal),retry:1});
 return <div><Header title="Настройки"><button className="button button-secondary" disabled={q.isFetching} onClick={()=>q.refetch()}>Обновить состояние</button></Header>{q.isPending?<p>Проверяем состояние сервисов…</p>:q.isError?<Failure error={q.error} retry={()=>q.refetch()}/>:<><section className="settings-panel"><h2>Состояние системы</h2><Checks checks={q.data.checks}/>{q.data.startup_error&&<p role="alert">{q.data.startup_error}</p>}</section><section className="environment-panel"><div><h2>Секреты и окружение</h2><p>{q.data.secret_instructions}</p>{q.data.limitations.map((s,i)=><p key={i}>{s}</p>)}</div><Link to="/targets" className="button button-secondary">Профили целей</Link></section></>}</div>;
}
